apiVersion: v1
kind: Pod
metadata:
  name: vllm-test
  namespace: assetswts  
spec:
  nodeSelector:
    kubernetes.io/hostname: llm25
  hostNetwork: true
  containers:
    - name: vllm-test
      image: 172.17.124.26:5000/aip/vllm/vllm-openai:v0.11.2
      command:
      - bash
      - -c
      - 'sleep infinity'
      resources:
        limits:
          nvidia.com/gpu: 2 # requesting 2 vGPUs
          # nvidia.com/gpumem-percentage: 50 # Each vGPU contains 50% device memory of that GPU （Optional,Integer）
          # nvidia.com/gpucores: 50 # Each vGPU uses 30% of the entire GPU （Optional,Integer)
          memory: "150Gi" # 请求的内存:q
          cpu: "5" # 请求的 CPU
        requests:
          memory: "5Gi" # 请求的内存
          cpu: "500m" # 请求的 CPU

      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /models
          name: sfs-pvc
          subPath: projs/assets/mwh/MWH-MODEL-d421qie7kgem4rtbc9d0/releases/MWH-MODEL-RELEASE-d421qru7kgem4rtbc9dg/model-files

  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 80Gi
    - name: sfs-pvc
      persistentVolumeClaim:
        claimName: sfs-pvc
  restartPolicy: Never
