apiVersion: v1
kind: Pod
metadata:
  name: qwen3.5-deploy
  labels:
    app: qwen3.5-deploy
spec:
  nodeSelector:
    kubernetes.io/hostname: llm31
  # hostNetwork: true
  containers:
    - name: qwen35-fp8-deploy
      image: llm31:5000/aip/sglang:v0.5.9-0226
      command:
      - bash
      - -c
      args:
      - |
        python -m sglang.launch_server --model Qwen/Qwen3.5-397B-A17B \
        --tp 8 --reasoning-parser qwen3 --tool-call-parser qwen3_coder --speculative-algo NEXTN \
        --speculative-num-steps 3 --speculative-eagle-topk 1 --speculative-num-draft-tokens 4 --mem-fraction-static 0.8 --port 8000 --host 0.0.0.0
      env:
      - name: CUDA_DISABLE_CONTROL
        value: "true"
      resources:
        limits:
          nvidia.com/gpu: 8 # requesting 2 vGPUs
          # nvidia.com/gpumem: 3000 # 每个 GPU 包含 3000m 设备内存
          # nvidia.com/gpumem-percentage: 50 # Each vGPU contains 50% device memory of that GPU （Optional,Integer）
          # nvidia.com/gpucores: 50 # Each vGPU uses 30% of the entire GPU （Optional,Integer)
          memory: "150Gi" # 请求的内存:q
          cpu: "12" # 请求的 CPU
        requests:
          nvidia.com/gpu: 8 # requesting 2 vGPUs
          # nvidia.com/gpumem: 3000 # 每个 GPU 包含 3000m 设备内存
          memory: "5Gi" # 请求的内存
          cpu: "500m" # 请求的 CPU

      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - name: nfs-vol
          mountPath: /models
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 80Gi
    - name: nfs-vol
      nfs:
        server: 172.17.124.30       # ← 这里换成你的 NFS 服务器 IP
        path: /mnt/nfs_server/models           # ← 这里换成你 NFS 上共享的目录
        readOnly: false
  restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-test-service
spec:
  type: NodePort
  selector:
    app: qwen3.5-deploy  # 匹配 Pod 的标签
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 32180
    name: sglang
    protocol: TCP