apiVersion: v1
kind: Service
metadata:
  name: ray-head
spec:
  selector:
    app: ray-head
  ports:
  - protocol: TCP
    name: ray-port
    port: 6379
    targetPort: 6379
  - protocol: TCP
    name: dashboard-port
    port: 8265
    targetPort: 8265
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray-head
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ray-head
  template:
    metadata:
      labels:
        app: ray-head
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dedicated
                operator: In
                values:
                - distributed-sglang
      containers:
      - name: ray-head
        image: llm226:5000/aip/vllm/vllm-openai:gptoss
        command: [ "/bin/bash", "-c" ]
        args:
        - |
          ray start --head --port=6379 --dashboard-host=0.0.0.0
          tail -f /dev/null
        ports:
        - containerPort: 6379
        - containerPort: 8265
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NCCL_DEBUG
          value: INFO
        - name: CUDA_DISABLE_CONTROL
          value: "true"
        resources:
          limits:
            rdma/hca_shared_devices_a: 1
            nvidia.com/gpu: 8
            memory: "200Gi"
            cpu: "10"
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /models
          name: nfs-vol
        securityContext:
          capabilities:
            add: ["IPC_LOCK"]
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 100Gi
        name: dshm
      - name: nfs-vol
        hostPath:
          path: /mnt/disk1/models
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: ray-worker-svc
spec:
  type: NodePort
  selector:
    app: ray-worker
  ports:
  - name: worker-port
    protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30203
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ray-worker
  template:
    metadata:
      labels:
        app: ray-worker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dedicated
                operator: In
                values:
                - distributed-sglang
      initContainers:
      - name: wait-for-ray
        image: llm226:5000/aip/deps/busybox:llm-1.4.3
        command: [ "/bin/sh", "-c" ]
        args: 
        - |
          echo "Checking if Ray head node is ready..."
          until nc -z ray-head 6379; do sleep 1; done
          echo "Ray head node is now ready!"
      containers:
      - name: ray-worker
        image: llm226:5000/aip/vllm/vllm-openai:gptoss
        command: [ "/bin/bash", "-c" ]
        args:
        - |
          echo "Waiting for Ray head node to be ready..."
          echo "Ray head node is ready!"
          ray start --address='ray-head:6379'
          vllm serve /models/DeepSeek-V3-0324 --served-model-name atom -tp 16 --enable-expert-parallel --trust-remote-code
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NCCL_DEBUG
          value: INFO
        - name: CUDA_DISABLE_CONTROL
          value: "true"
        resources:
          limits:
            rdma/hca_shared_devices_a: 1
            nvidia.com/gpu: 8
            memory: "200Gi"
            cpu: "10"
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /models
          name: nfs-vol
        securityContext:
          capabilities:
            add: ["IPC_LOCK"]
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 100Gi
        name: dshm
      - name: nfs-vol
        hostPath:
          path: /mnt/disk1/models
          type: Directory
