---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-lb-main
  labels:
    app: vllm-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-lb
  template:
    metadata:
      labels:
        app: vllm-lb
    spec:
      containers:
        - name: vllm-minilb
          image: harbor.transwarp.io/aip-amd/xpu-nvidia/vllm-openai:v0.11.2
          command:
            - bash
            - -c
            - |
              cd /vllm-workspace/examples/online_serving/disaggregated_serving_p2p_nccl_xpyd && \
              python3 disagg_prefill_proxy_server.py
          ports:
            - containerPort: 30001
            - containerPort: 10001

---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  type: NodePort # NodePort is easy to test, you can also specify `ClusterIP`
  selector:
    app: vllm-lb
  ports:
    - name: proxy
      protocol: TCP
      port: 30001         # Service Port（In-Cluster）
      targetPort: 30001   # Exposed Container
    - name: http
      protocol: TCP
      port: 10001
      targetPort: 10001  
      nodePort: 31001    
---
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: vllm-prefill
spec:
  replicas: 1 # The number of pods.
  startupPolicy: LeaderCreated
  rolloutStrategy:
    type: RollingUpdate
    rollingUpdateConfiguration:
      maxSurge: 0
      maxUnavailable: 2 # Enable the MaxUnavailableStatefulSet feature gate.
  leaderWorkerTemplate:
    size: 1
    restartPolicy: RecreateGroupOnPodRestart
    workerTemplate:
      metadata:
        labels:
          role: leader
      spec:
        nodeSelector:
          kubernetes.io/hostname: dev32
        containers:
          - name: vllm-prefill
            image: harbor.transwarp.io/aip-amd/xpu-nvidia/vllm-openai:v0.11.2
            imagePullPolicy: IfNotPresent
            env:
              - name: NCCL_DEBUG
                value: INFO
              - name: VLLM_LOGGING_LEVEL
                value: DEBUG
              - name: VLLM_TRACE_FUNCTION
                value: "1"
            # workingDir: /sgl-workspace
            command:
              - bash
              - -c
              - |
                VLLM_USE_V1=1 vllm serve /models/Qwen/Qwen2.5-7B-Instruct/ \
                  -tp 1 \
                  --host 0.0.0.0 \
                  --port 20001 \
                  --trust-remote-code \
                  --max-model-len 10000 \
                  --max-num-batched-tokens 10000 \
                  --max-num-seqs 256 \
                  --gpu-memory-utilization 0.9 \
                  --served-model-name atom \
                  --kv-transfer-config '{"kv_connector":"P2pNcclConnector","kv_role":"kv_consumer","kv_buffer_size":"8e9","kv_port":"22001","kv_connector_extra_config":{"proxy_ip":"proxy-service","proxy_port":"30001","http_port":"20002"}}'
            ports:
            - containerPort: 20001
              name: http
              protocol: TCP
            - containerPort: 21001
            resources:
              limits:
                nvidia.com/gpu: "1"
                rdma/hca_shared_devices_a: 1
                #vke.volcengine.com/infiniband-rdma: "8"  # Use this parameter for H100's InfiniBand RDMA.
              requests:
                nvidia.com/gpu: "1"
                rdma/hca_shared_devices_a: 1
                #vke.volcengine.com/infiniband-rdma: "8"  # Use this parameter for H100's InfiniBand RDMA.
            securityContext:
              capabilities:
                add:
                - IPC_LOCK
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /dev/shm
                name: dshm
              - name: nfs-vol
                mountPath: /models
        volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 50Gi
        - name: nfs-vol
          nfs:
            server: 172.17.124.32       # ← 这里换成你的 NFS 服务器 IP
            path: /mnt/disk1/zty/models           # ← 这里换成你 NFS 上共享的目录
            readOnly: false
---
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: vllm-decode
spec:
  replicas: 1 # The number of pods.
  startupPolicy: LeaderCreated
  rolloutStrategy:
    type: RollingUpdate
    rollingUpdateConfiguration:
      maxSurge: 0
      maxUnavailable: 2 # Enable the MaxUnavailableStatefulSet feature gate.
  leaderWorkerTemplate:
    size: 1
    restartPolicy: RecreateGroupOnPodRestart
    workerTemplate:
      metadata:
        labels:
          role: leader
      spec:
        nodeSelector:
          kubernetes.io/hostname: dev32
        containers:
          - name: vllm-decode
            image: harbor.transwarp.io/aip-amd/xpu-nvidia/vllm-openai:v0.11.2
            imagePullPolicy: IfNotPresent
            env:
              - name: NCCL_DEBUG
                value: INFO
              - name: VLLM_LOGGING_LEVEL
                value: DEBUG
              - name: VLLM_TRACE_FUNCTION
                value: "1"
            # workingDir: /sgl-workspace
            command:
              - bash
              - -c
              - |
                VLLM_USE_V1=1 vllm serve /models/Qwen/Qwen2.5-7B-Instruct/ \
                  -tp 1 \
                  --host 0.0.0.0 \
                  --port 20002 \
                  --trust-remote-code \
                  --gpu-memory-utilization 0.7 \
                  --served-model-name atom \
                  --kv-transfer-config '{"kv_connector":"P2pNcclConnector","kv_role":"kv_producer","kv_buffer_size":"1e1","kv_port":"21001","kv_connector_extra_config":{"proxy_ip":"proxy-service","proxy_port":"30001","http_port":"20001"}} '
            ports:
            - containerPort: 20002
              name: http
              protocol: TCP
            - containerPort: 22001
            resources:
              limits:
                nvidia.com/gpu: "1"
                rdma/hca_shared_devices_a: 1
                #vke.volcengine.com/infiniband-rdma: "8"  # Use this parameter for H100's InfiniBand RDMA.
              requests:
                nvidia.com/gpu: "1"
                rdma/hca_shared_devices_a: 1
                #vke.volcengine.com/infiniband-rdma: "8"  # Use this parameter for H100's InfiniBand RDMA.
            securityContext:
              capabilities:
                add:
                - IPC_LOCK
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /dev/shm
                name: dshm
              - name: nfs-vol
                mountPath: /models
              
        volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 50Gi
        - name: nfs-vol
          nfs:
            server: 172.17.124.32       # ← 这里换成你的 NFS 服务器 IP
            path: /mnt/disk1/zty/models           # ← 这里换成你 NFS 上共享的目录
            readOnly: false

